### ISSUE TITLE
MCU alternatives

### ISSUE THREAD

**Issue by fi0** [customMK/Bonsai-C#4]
The STM32F411 is out of stock on JLCPCB.
Is STM32F401CCU6, STM32F303CBT6, or GD32F303CCT6 (bluepill plus) compatible with C4? or should I use C3?

**Comment by infinityis** [comment]
Whenever STM32F411 is out of stock at JLCPCB, you can either build Bonsai C3 using STM32F303CBT6 (noting that CBT6 has half the flash memory of CCT6), or you can build Bonsai C4 using STM32F401CCU6 instead (but be aware that QMK configurations for Bonsai C4 won't apply...for example the clock speed settings in mcuconf.h would need to change because F401 operates at a lower frequency than F411)

If you are just planning to build Bonsai C4 as-is, you can also purchase them pre-assembled from customMK, which costs less than making them through JLCPCB.
